### ISSUE TITLE
Tokens with no return value from `approve` function do not work with v3 paraswap adapters

### ISSUE THREAD

**Issue by grothem** [aave/aave-v3-periphery#174]
Tokens that do not return a value from the `approve` function do not work with the paraswap adapters, such as USDT. Currently, GPv2SafeERC20 is being used to wrap ERC20s, but there is no `approve` in the library.

Look at using OZ's SafeERC20 which handles no return value, and assumes it is successful if there is no revert.

**Comment by miguelmtzinf** [comment]
Closed by #176
