### ISSUE TITLE
How should I deploy the UiPoolDataProviderV3 and UiIncentiveDataProviderV3 contracts?

### ISSUE THREAD

**Issue by aansheng** [aave/aave-v3-periphery#86]

**Comment by miguelmtzinf** [comment]
@aansheng I suggest you to use [hardhat-deploy](https://github.com/wighawag/hardhat-deploy), [hardhat](https://hardhat.org/hardhat-runner/docs/guides/deploying) or even plain [ethers.js](https://docs.ethers.io/v4/api-contract.html) code
